import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import ScrollProgress from "@/components/ScrollProgress";
import { CheckCircle, Play, TrendingUp, Star } from "lucide-react";

const SuccessStoriesPage = () => {
  const stories = [
    {
      title: "AztroGrizz",
      subtitle: "1,156 New Subscribers in 10 days",
      image: "/lovable-uploads/3.webp",
      goal: "A multi-genre music duo wanted more fans from the Colorado state area.",
      results: [
        "Vidflyy's algorithm successfully generated 1,156 subscribers, 84 comments, 373 playlist additions, and 667 likes from 20,099 ad views.",
        "Users who clicked Vidflyy's ad revisited the channel leading to 5,368 additional (free) views. This number is continuing to increase.",
        "Vidflyy's algorithm found the highest response rate came from males located in Denver, CO, ages 18-34, with an affinity for Outdoor Sports.",
        "Client has seen an increase in Spotify plays and monthly listeners since their Vidflyy promotion."
      ]
    },
    {
      title: "GolfTEC.com",
      subtitle: "143,535 Additional Subscribers",
      image: "/lovable-uploads/4.jpg",
      goal: "International golf brand wants to increase awareness on YouTube.",
      results: [
        "Vidflyy successfully grew GolfTec's subscribers from 12,000 to over 155,000 (and counting).",
        "With the momentum generated by Vidflyy's promotions, GolfTec's channel is now growing by over 500 new subscribers per day.",
        "GolfTec has successfully generated over 15.3 million viewers (and counting).",
        "Vidflyy's algorithm found the highest response rate from males, ages 25-54, actively watching videos related to golf tips for beginners."
      ]
    },
    {
      title: "Children's Channel",
      subtitle: "Grows from 66 to 3,670 Subscribers",
      image: "/lovable-uploads/62dd2f69-c830-4347-b995-736dbba52b6d.png",
      goal: "Children's products brand aims to grow following quickly.",
      results: [
        "Vidflyy quickly grew Zoopy Zoom's subscribers from 66 to over 3,670 in only 9 days.",
        "The channel has seen a large increase in engagement on its new videos.",
        "Vidflyy's algorithm found the highest response rate by targeting new mothers, females, ages 25-44, actively watching videos featuring children's content."
      ]
    }
  ];

  return (
    <div className="min-h-screen bg-white font-montserrat">
      <Navbar />
      
      {/* Hero Section */}
      <section className="py-20 bg-gradient-to-br from-red-50 to-white relative overflow-hidden">
        <div className="absolute inset-0">
          <div className="absolute top-10 left-10 w-32 h-32 bg-red-50 rounded-full opacity-30 animate-pulse"></div>
          <div className="absolute top-1/2 right-20 w-24 h-24 bg-red-100 rounded-full opacity-40 animate-bounce"></div>
          <div className="absolute bottom-20 left-1/3 w-40 h-40 bg-red-50 rounded-full opacity-20 animate-pulse"></div>
        </div>
        
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 relative z-10">
          <div className="text-center mb-16">
            <h1 className="text-4xl lg:text-5xl font-bold text-gray-900 mb-6 animate-fade-in">
              Success <span className="text-red-600">Stories</span>
            </h1>
            <p className="text-xl text-gray-600 max-w-3xl mx-auto animate-fade-in">
              Real Results from 2024: See how Vidflyy helped YouTubers like you achieve their growth goals. 
              Our clients have seen significant increases in views, subscribers, and engagement.
            </p>
          </div>
        </div>
      </section>

      {/* Success Stories Content */}
      <section className="py-20 bg-white">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="space-y-16">
            {stories.map((story, index) => (
              <div key={index} className={`grid lg:grid-cols-2 gap-12 items-center ${index % 2 === 1 ? 'lg:grid-flow-col-dense' : ''}`}>
                <div className={`${index % 2 === 1 ? 'lg:col-start-2' : ''} animate-fade-in`}>
                  <div className="bg-white rounded-2xl shadow-lg overflow-hidden hover:shadow-2xl transition-all duration-500 hover:scale-105">
                    <img 
                      src={story.image} 
                      alt={story.title}
                      className="w-full h-64 object-cover"
                    />
                    <div className="p-6">
                      <h3 className="text-2xl font-bold text-gray-900 mb-2">{story.title}</h3>
                      <p className="text-red-600 font-semibold text-lg mb-4">{story.subtitle}</p>
                      <div className="flex items-center gap-2 text-sm text-gray-600">
                        <Play className="h-4 w-4" />
                        <span>View Campaign Report</span>
                      </div>
                    </div>
                  </div>
                </div>
                
                <div className={`${index % 2 === 1 ? 'lg:col-start-1 lg:row-start-1' : ''} animate-fade-in`}>
                  <div className="mb-6">
                    <h4 className="text-lg font-semibold text-gray-900 mb-3">Goal:</h4>
                    <p className="text-gray-700">{story.goal}</p>
                  </div>
                  
                  <div className="space-y-4">
                    <h4 className="text-lg font-semibold text-gray-900">Results:</h4>
                    {story.results.map((result, resultIndex) => (
                      <div key={resultIndex} className="flex items-start gap-3">
                        <CheckCircle className="h-5 w-5 text-red-600 mt-1 flex-shrink-0" />
                        <p className="text-gray-700 leading-relaxed">{result}</p>
                      </div>
                    ))}
                  </div>
                </div>
              </div>
            ))}
          </div>
          
          {/* Testimonials Section */}
          <div className="mt-20">
            <div className="text-center mb-12">
              <h2 className="text-3xl lg:text-4xl font-bold text-gray-900 mb-4">
                What Our <span className="text-red-600">Clients Say</span>
              </h2>
              <div className="flex items-center justify-center gap-2 mb-4">
                <div className="flex text-yellow-400">
                  {[...Array(5)].map((_, i) => (
                    <Star key={i} className="h-6 w-6 fill-current" />
                  ))}
                </div>
                <span className="text-gray-600 ml-2">5.0 Google Rating</span>
              </div>
            </div>
            
            <div className="grid md:grid-cols-3 gap-8">
              {[
                {
                  name: "Sarah Johnson",
                  role: "Beauty YouTuber",
                  content: "Vidflyy helped me grow from 500 to 50,000 subscribers in just 6 months. The targeting was incredibly precise!",
                  rating: 5
                },
                {
                  name: "Mike Chen",
                  role: "Tech Reviewer",
                  content: "The best investment I made for my channel. Professional service and amazing results that exceeded expectations.",
                  rating: 5
                },
                {
                  name: "Emma Wilson",
                  role: "Lifestyle Vlogger",
                  content: "Outstanding service! My engagement rates doubled and subscriber quality improved significantly.",
                  rating: 5
                }
              ].map((testimonial, index) => (
                <div key={index} className="bg-white p-6 rounded-2xl shadow-lg hover:shadow-xl transition-all duration-300 animate-fade-in">
                  <div className="flex text-yellow-400 mb-4">
                    {[...Array(testimonial.rating)].map((_, i) => (
                      <Star key={i} className="h-5 w-5 fill-current" />
                    ))}
                  </div>
                  <p className="text-gray-700 mb-6 italic">"{testimonial.content}"</p>
                  <div>
                    <h4 className="font-semibold text-gray-900">{testimonial.name}</h4>
                    <p className="text-gray-600 text-sm">{testimonial.role}</p>
                  </div>
                </div>
              ))}
            </div>
          </div>
          
          <div className="text-center mt-16">
            <div className="bg-red-50 rounded-2xl p-8 inline-block">
              <TrendingUp className="h-12 w-12 text-red-600 mx-auto mb-4" />
              <h3 className="text-xl font-bold text-gray-900 mb-2">Ready to Be Our Next Success Story?</h3>
              <p className="text-gray-600">Join thousands of creators who've achieved remarkable growth with Vidflyy</p>
            </div>
          </div>
        </div>
      </section>

      <Footer />
      <ScrollProgress />
    </div>
  );
};

export default SuccessStoriesPage;