export const promotionPackages = [
    {
        id: "starter",
        name: "Starter",
        price: 999,
        views: 5000,
        hasAI: false,
        accent: "bg-blue-50",
        borderColor: "border-blue-200",
    },
    {
        id: "boost",
        name: "Boost",
        price: 1999,
        views: 10000,
        hasAI: false,
        accent: "bg-green-50",
        borderColor: "border-green-200",
    },
    {
        id: "growth",
        name: "Growth",
        price: 3499,
        views: 20000,
        hasAI: false,
        accent: "bg-purple-50",
        borderColor: "border-purple-200",
    },
    {
        id: "premium-ai",
        name: "Premium AI",
        price: 5499,
        views: 35000,
        bonusViews: 2000,
        totalViews: 37000,
        hasAI: true,
        discount: 5,
        aiFeatures: ["AI Smart Targeting for precise audience reach", "Higher watch time & stronger engagement"],
        accent: "bg-orange-50",
        borderColor: "border-orange-300",
        isPopular: true,
    },
    {
        id: "viral-ai",
        name: "Viral AI",
        price: 8999,
        views: 55000,
        bonusViews: 4000,
        totalViews: 59000,
        hasAI: true,
        discount: 8,
        aiFeatures: ["Advanced AI Interest Targeting", "Optimized placements for rapid growth"],
        accent: "bg-red-50",
        borderColor: "border-red-300",
    },
    {
        id: "ultra-viral-ai",
        name: "Ultra Viral AI",
        price: 12999,
        views: 80000,
        bonusViews: 6500,
        totalViews: 86500,
        hasAI: true,
        discount: 10,
        aiFeatures: ["AI Behaviour + Interest + Demographic Targeting", "Maximum reach & best viral potential"],
        accent: "bg-gradient-to-br from-purple-50 to-pink-50",
        borderColor: "border-purple-400",
        isPremium: true,
    },
];
